# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build -t my-app:${{ github.sha }} .          
      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0
        with:
          image: 'docker.io/my-app:${{ github.sha }}'
          output-file: 'sbom.json'
          output-format: 'spdx-json'

      - name: Scan SBOM with Grype
        uses: anchore/scan-action@v6
        with:
          sbom: 'sbom.json'       
          output-format: table     
          only-fixed: true       
