# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build an image from Dockerfile
        run: |
          docker build -t my-app:${{ github.sha }} .   
          
      - name: Scan Image
        uses: anchore/scan-action@v6
        id: scan
        with:
          image: my-image:${{ github.sha }}  
          fail-build: false
          severity-cutoff: high      # or critical/high/low/negligible
          output-format: sarif

      
